"""Dense-teacher SFT targets, and the filters that decide which ones are usable.

Every SFT target here is generated by the unpruned dense Qwen3-8B rather than
taken from a dataset. That is a deliberate constraint, not a convenience: the
recovery objective is "restore *this* model's reasoning behavior", so the target
distribution has to be this model's own. A third-party answer -- however
correct -- teaches a different policy, and PASER measured the cost of getting this
wrong (recovery on bulk third-party instruction data drove perplexity from 20 to
736).

Generation itself is delegated to ``offline_teacher.generate_shared_teacher_sequences``,
which already handles sharded caching, mid-run resume, and truncation filtering.
What this module adds is the rest of the spec's filter list -- empty, degenerate,
and format-violating responses -- plus the domain accounting the pruning comparison
table needs.

**Why a repetition filter matters here.** A pruned model's characteristic failure
is looping, and the V1 numbers show the mechanism: pruned-model truncation ran at
99.6% before recovery, and OPD's main measured effect was reducing truncation
rather than improving reasoning. A looping teacher response is worse than a
missing one, because sequence-level SFT would fit the loop directly. The same
n-gram statistic is reported by the benchmark suite, so teacher data and student
output are judged by one definition.
"""

from __future__ import annotations

import json
from collections import Counter
from pathlib import Path
from typing import Any

import pandas as pd

from recal.common import dump_json, utc_now
from recal.data.offline_teacher import generate_shared_teacher_sequences
from recal.data.prompt_formats import response_has_expected_format
from recal.modes import THINK_CLOSE, THINK_OPEN

# A 32-token window is long enough that natural restatement does not trigger it
# and short enough to catch a looping tail. Judged over the post-</think> answer
# and the reasoning block alike, since either can degenerate.
DEFAULT_REPETITION_NGRAM = 32
# Fraction of repeated n-gram positions above which a response is degenerate.
# Reasoning traces legitimately repeat structure ("Let me reconsider...", restated
# equations), so this sits well above prose-level repetition; it targets responses
# that are mostly loop.
DEFAULT_REPETITION_THRESHOLD = 0.35


def repetition_rate(text: str, *, ngram: int = DEFAULT_REPETITION_NGRAM) -> float:
    """Fraction of n-gram positions whose n-gram appeared earlier in the text.

    Word-level (not token-level) so it is computable without a tokenizer, which
    lets the benchmark suite reuse it on generations it has only as strings.
    Returns 0.0 for text too short to contain one n-gram.
    """
    words = str(text).split()
    if len(words) < ngram:
        return 0.0
    total = len(words) - ngram + 1
    counts: Counter[str] = Counter()
    for index in range(total):
        counts[" ".join(words[index : index + ngram])] += 1
    repeated = sum(count - 1 for count in counts.values() if count > 1)
    return repeated / total


def _reasoning_and_answer(response: str) -> tuple[str, str]:
    """Split a thinking-mode response into its reasoning block and its answer."""
    text = str(response)
    if THINK_CLOSE in text:
        head, _, tail = text.partition(THINK_CLOSE)
        return head.replace(THINK_OPEN, ""), tail
    return "", text


def classify_teacher_response(
    response: str,
    *,
    domain: str,
    thinking_enabled: bool,
    repetition_threshold: float = DEFAULT_REPETITION_THRESHOLD,
    ngram: int = DEFAULT_REPETITION_NGRAM,
) -> dict[str, Any]:
    """Judge one teacher response, returning the verdict and the evidence.

    Reasons are returned as a list rather than a single verdict so the manifest can
    report *why* a domain lost rows. V1's silent 50% code loss to the length cap was
    only understood after the fact; per-reason counts make that visible while the
    build is still running.
    """
    text = str(response or "")
    reasons: list[str] = []
    if not text.strip():
        reasons.append("empty")
    reasoning, answer = _reasoning_and_answer(text)

    if thinking_enabled:
        # An unclosed </think> means the response never left the reasoning block.
        # Training on it teaches the student not to stop thinking -- exactly the
        # failure the truncation metric tracks.
        if THINK_CLOSE not in text:
            reasons.append("unclosed_think")
        elif not answer.strip():
            reasons.append("empty_answer_after_think")

    # The grader extracts a specific form; a response that never emits it is
    # unusable as a target regardless of how good the reasoning is. Judged on the
    # answer span when there is one, so a \boxed{} that appears only inside the
    # discarded reasoning does not count as a pass.
    scored_span = answer if (thinking_enabled and THINK_CLOSE in text) else text
    if not response_has_expected_format(scored_span, domain):
        reasons.append("format_missing")

    rates = {
        "response": repetition_rate(text, ngram=ngram),
        "reasoning": repetition_rate(reasoning, ngram=ngram) if reasoning else 0.0,
        "answer": repetition_rate(answer, ngram=ngram) if answer else 0.0,
    }
    if max(rates.values()) >= repetition_threshold:
        reasons.append("degenerate_repetition")

    return {
        "usable": not reasons,
        "reasons": reasons,
        "repetition_rate": round(rates["response"], 4),
        "repetition_rate_reasoning": round(rates["reasoning"], 4),
        "repetition_rate_answer": round(rates["answer"], 4),
    }


def filter_teacher_frame(
    frame: pd.DataFrame,
    *,
    thinking_enabled: bool,
    repetition_threshold: float = DEFAULT_REPETITION_THRESHOLD,
    ngram: int = DEFAULT_REPETITION_NGRAM,
) -> tuple[pd.DataFrame, pd.DataFrame, dict[str, Any]]:
    """Apply the quality filters, returning (retained, rejected, statistics)."""
    verdicts = [
        classify_teacher_response(
            record["teacher_response"],
            domain=str(record["domain"]),
            thinking_enabled=thinking_enabled,
            repetition_threshold=repetition_threshold,
            ngram=ngram,
        )
        for record in frame.to_dict("records")
    ]
    annotated = frame.copy()
    annotated["quality_usable"] = [verdict["usable"] for verdict in verdicts]
    annotated["quality_reasons"] = [",".join(verdict["reasons"]) for verdict in verdicts]
    for column in ("repetition_rate", "repetition_rate_reasoning", "repetition_rate_answer"):
        annotated[column] = [verdict[column] for verdict in verdicts]

    retained = annotated[annotated["quality_usable"]].drop(columns=["quality_usable"])
    rejected = annotated[~annotated["quality_usable"]].drop(columns=["quality_usable"])

    reason_counts: Counter[str] = Counter()
    per_domain_reasons: dict[str, Counter[str]] = {}
    for record, verdict in zip(frame.to_dict("records"), verdicts):
        domain = str(record["domain"])
        per_domain_reasons.setdefault(domain, Counter())
        for reason in verdict["reasons"]:
            reason_counts[reason] += 1
            per_domain_reasons[domain][reason] += 1

    statistics = {
        "input_rows": int(len(frame)),
        "retained_rows": int(len(retained)),
        "rejected_rows": int(len(rejected)),
        "retention_rate": round(len(retained) / len(frame), 4) if len(frame) else 0.0,
        "rejected_by_reason": dict(sorted(reason_counts.items())),
        "rejected_by_domain": {
            domain: dict(sorted(counts.items()))
            for domain, counts in sorted(per_domain_reasons.items())
        },
        "repetition_threshold": repetition_threshold,
        "repetition_ngram": ngram,
    }
    return retained.reset_index(drop=True), rejected.reset_index(drop=True), statistics


def domain_token_accounting(frame: pd.DataFrame) -> dict[str, Any]:
    """Prompt and response-token shares per domain.

    Both are reported because they diverge sharply and the token view is the one
    the model actually experiences: V1's pool was 40.9% math by prompt count but
    61.2% by response token, since math and code traces run several times longer
    than instruction-following ones. The pool builder balances prompt counts first and
    escalates to a token-balanced sampler only if a domain exceeds ~40% of tokens,
    so this is the measurement that decides whether that second version is needed.
    """
    tokens = frame["teacher_response_tokens"].astype(int)
    total_tokens = int(tokens.sum())
    accounting: dict[str, Any] = {
        "prompt_count_by_domain": {},
        "response_tokens_by_domain": {},
        "response_token_share_by_domain": {},
        "mean_response_tokens_by_domain": {},
        "total_response_tokens": total_tokens,
    }
    for domain in sorted(frame["domain"].astype(str).unique()):
        selector = frame["domain"].astype(str) == domain
        domain_tokens = int(tokens[selector].sum())
        accounting["prompt_count_by_domain"][domain] = int(selector.sum())
        accounting["response_tokens_by_domain"][domain] = domain_tokens
        accounting["response_token_share_by_domain"][domain] = (
            round(domain_tokens / total_tokens, 4) if total_tokens else 0.0
        )
        accounting["mean_response_tokens_by_domain"][domain] = (
            round(float(tokens[selector].mean()), 1) if selector.any() else 0.0
        )
    return accounting


def build_sft_targets(config: dict[str, Any]) -> dict[str, Any]:
    """Generate dense-teacher targets for the balanced SFT pool and filter them.

    ``generate_shared_teacher_sequences`` writes the raw parquet (and drops
    length-truncated rows); this adds the quality pass and writes the final
    training file the trainer reads.
    """
    data = config["data"]
    raw_path = Path(data["sft_teacher_raw_path"])
    final_path = Path(data["sft_teacher_path"])
    success_path = final_path.with_suffix(".quality.json")

    # Point the generator at the raw path; the filtered file is this module's
    # product, and conflating the two would make the generator's resume check
    # compare against a file it did not write.
    generation_config = dict(config)
    generation_config["data"] = {**data, "sft_teacher_path": str(raw_path)}
    generation_manifest = generate_shared_teacher_sequences(generation_config)

    thinking = bool(config.get("model", {}).get("thinking_enabled", True))
    settings = config.get("offline_teacher", {}) or {}
    frame = pd.read_parquet(raw_path)
    retained, rejected, statistics = filter_teacher_frame(
        frame,
        thinking_enabled=thinking,
        repetition_threshold=float(
            settings.get("repetition_threshold", DEFAULT_REPETITION_THRESHOLD)
        ),
        ngram=int(settings.get("repetition_ngram", DEFAULT_REPETITION_NGRAM)),
    )
    if retained.empty:
        raise RuntimeError("Every teacher response failed the quality filters")

    final_path.parent.mkdir(parents=True, exist_ok=True)
    retained.to_parquet(final_path, index=False)
    if len(rejected):
        rejected.to_parquet(final_path.with_suffix(".rejected.parquet"), index=False)

    summary = {
        "status": "completed",
        "created_at": utc_now(),
        "raw_path": str(raw_path),
        "output": str(final_path),
        "generation": generation_manifest,
        "quality": statistics,
        "accounting": domain_token_accounting(retained),
        "thinking_enabled": thinking,
    }
    dump_json(summary, success_path)
    return summary


def main() -> None:
    import argparse

    from recal.common import load_yaml

    parser = argparse.ArgumentParser()
    parser.add_argument("--config", required=True)
    args = parser.parse_args()
    print(json.dumps(build_sft_targets(load_yaml(args.config)), indent=2))


if __name__ == "__main__":
    main()
